language: python
deploy:
  provider: heroku
  api_key:
    secure: I3xgJ0oIzms153gv/oQMQVQfQixYDKsS13ONHT5JAbNtFP5aitwqwUTqCtbl2y3SYyPCxSRDOTkgy2UZRVqpgdCw51NHTNCAg6PrxsP3hvZZ4bUwrF9PRTG96wCZL6Gdyafp3HcZtCXUA0ca7fcHpjBTS52CTXvsp+aP248VS4qX4aegAW37SB8Zj8LTsqIfpusAk4eGH6ubVb7H2Mo82PZO1RvwK9cRbPwqPCKVfbmwhBx3JxiqnllVOoX+Y/DZ+i0cAsYA9lETsSNP2Ms9eb1YdBusx/lkvwBybadojCEq/b+7AhDOBGW4sHh1wKFAr3CRbtdy3rUw3orIbQxB2FG44mgVaKWnkZUgRnMmu6t88NYzeTz6Eohm0FJFH6SepEcgFLJ/ofk4+aU962ChjFOyXQCT8GbwbkDcs+BGyLLeFA78Gf80BVDbcSgmNj2KxEvq38vM6sPONi9Y2cYzaaXVhoYscYgjYu8xaFdMnSPfUYxBnEewIekHE+KbTISq+Q7HeA7SkgR1wtVs1m4xjdGbGWJflOC/Fgjyrmw02Cki1H2eAjRMB/gdeb4vL1taXebyo+4TvGui/Lzly0ZZkhI9lgWbENWFNBa3iEMYgwjbwTwvLbU5SAAtsnYQR4tfLN798ooyiQ1Ore4pSsPrxEgGGLMvp4L3+XafW4kqQUQ=
  app: steleforest
  on:
    repo: mathiasleborgne/chinese-texts
script: "pwd"